### ISSUE TITLE
For universal app with both portrait and landscape. not support perfect if use size 

### ISSUE THREAD

**Issue by jerryzhoujw** [TimurBK/UIImage-XCAssets#2]
```
 - (void)viewWillTransitionToSize:(CGSize)size withTransitionCoordinator: (id<UIViewControllerTransitionCoordinator>  __unused)coordinator {
     [self.backgroundImageView setImage:[UIImage assetLaunchImageWithSize:size  useSystemCache:YES]];
 }
```

the code above works perfect when I rotate the iPad, but for iPhone5s, when rotate to landscape, the background image still get from portrait image.

PS: 
a.App support iOS8+
b.I use imageAsset launchImage to include bellow:  
   iOS8 and Later:iPhone Portrait 
                                          Landscape
    iOS7 and Later:iPhone Portrait
                                 iPad Portrait
                                          Landscape

**Comment by TimurBK** [comment]
@jerryzhoujw Thank you for your report, I'll look at this issue soon.

**Comment by jerryzhoujw** [comment]
@TimurBK  I think properly because LaunchImage is not supported for iPhone4/5/6(excepted 6plus) in landscape mode. 
I use the temp solution bellow:

```
// iPhone6s {736, 414}
// iPhone6  {667, 375}
// iPhone5S {568, 320}
// iPhone5  {568, 320}
// iPhone4s {480, 320}
// NOTE: for iPhone4/4s/5/5s/6 LaunchImage don't include the Landscape mode.
if (size.width > size.height &&
    size.width <= 667) {
    [self.backgroundImageView setImage:[UIImage imageNamed:[NSString stringWithFormat:@"Default-Landscape-iPhone-%d",(int)size.width]]];
}else{
    [self.backgroundImageView setImage:[UIImage assetLaunchImageWithSize:size useSystemCache:YES]];
}
```

**Comment by TimurBK** [comment]
During creation of image name string I check that it's iPhone 6+ or iPad because there's no landscape launch images for smaller iPhones. Maybe there should be an option to disable this check so category will find this, but technically this is another image set.

**Comment by TimurBK** [comment]
Will close this and open separate issue for enhancement.
